# Expose your documentation as JSON swagger compliant
nelmio_api_doc:
    documentation:
        info:
            title: 'Api Rest Con Symfony'
            description: "Mi app UwU"
            version: 1.0.0
  #  app.swagger:
   #     path: /api/doc.json
    #    methods: GET
     #   defaults: { _controller: nelmio_api_doc.controller.swagger }

